### ISSUE TITLE
使用OpenAI的时候 ，会提示 未配置 OpenAI 的 Endpoint 输出 。

### ISSUE THREAD

**Issue by onestar1** [Senparc/Senparc.AI#61]
使用OpenAI的时候 ，会提示 未配置 OpenAI 的 Endpoint 输出 。
是否要加一个openai的endpoint参数配置
![image](https://github.com/Senparc/Senparc.AI/assets/10646303/c60e6a9f-c2c8-459f-8173-93278e4324c4)

**Comment by JeffreySu** [comment]
@onestar1 请同步最新版本，已经添加，并且所有模型可以通过 appsettings.json 进行配置，请参考 Sample，谢谢支持！
