### ISSUE TITLE
尝试添加一个讯飞的ai对接。

### ISSUE THREAD

**Issue by onestar1** [Senparc/Senparc.AI#83]
要是有关于Senparc.AI.Kernel 的 Extensions.cs 的介绍就好了。 现在看都是基于openai的
包括fastapi。  毕竟国内对接文心一言 还有 讯飞等的会比较多，通用。
我这太简单的实现，估计是不够规范，暂时只实现了文字对话。 请苏大佬指点下 
![image](https://github.com/Senparc/Senparc.AI/assets/10646303/9b4a33ac-00ca-43e4-a5ba-6fe2536eb3c0)
![image](https://github.com/Senparc/Senparc.AI/assets/10646303/28443970-4a81-44cb-84a0-7f09df561e92)
![image](https://github.com/Senparc/Senparc.AI/assets/10646303/0e4ca497-7e35-4255-9464-e84d89934bae)

![image](https://github.com/Senparc/Senparc.AI/assets/10646303/a5442400-4d41-41a3-881d-425805a69a62)

**Comment by JeffreySu** [comment]
@onestar1 做法有挺多的，基本上都是参考 SK 几个 Connector 的写法，你也可以 PR 你的方案上来一起看一下，后面我们会整理文档的。谢谢！
